import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Button } from "antd";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full h-10 bg-red-500 text-3xl flex justify-around">
          {" "}
          <Link href="/about">
            <Button type="primary">About</Button>
          </Link>
          <Link href="/news">
            <Button type="primary">News</Button>
          </Link>
          <Link href="/news/blog">
            <Button type="primary">Blog with nested route</Button>
          </Link>
          <Link href="/productPage/15">
            <Button type="primary">dynamic route with single id</Button>
          </Link>
          <Link href="/productPage/15/42/55">
            <Button type="primary">dynamic route with multiple id / catch all route</Button>
          </Link>
        </div>
        {children}
      </body>
    </html>
  );
}
